version: '3'

services:
  postgres-db:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=infoKray
    ports:
      - '5432:5432'